### ISSUE TITLE
Can not get  flnc.tmap file

### ISSUE THREAD

**Issue by RyanYip-Kat** [shizhuoxing/scIsoSeq-Analysis-Tools#1]
When I run command: gffcompare -r ref.genes.gtf isoseq_flnc.Transcript.gff -o flnc
I can not get the flnc.tmap
And I also want to know what is your ref.gene.gtf

**Comment by shizhuoxing** [comment]
Hi，Ryan
In generally, you can download the gene annotation gtf file specific for your own data on Ensembl, Genecode or NCBI for one species.
For this repo I uploaded example CCS data, the species is the cynomolgus monkey, which is consistent with our preprint paper.
May be when you set the right of “ref.gene.gtf” file for gffcompare you can get the flnc.tmap, by the way, gffcompare output the flnc.tmap file to the same path with you "isoseq_flnc.Transcript.gff".

**Comment by RyanYip-Kat** [comment]
But When I used the  *css.bam data you provided in the example_data ,and my genome is : Macaca_fascicularis.Macaca_fascicularis_5.0.dna.toplevel.fa,gtf file is  Macaca_fascicularis.Macaca_fascicularis_5.0.100.gtf.I can not get the *.h5 file with your pipeline  scripts.And I always got the error when  I used sqanti3_qc.py,the error like : 
  **** Predicting ORF sequences...
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
GeneMarkS: error on last system call, error code 134
Abort program!!!
 And the *.isoform.matrix is NULL .And how can I fixed these issue ! Thanks!

**Comment by pigraul** [comment]
Hello, I ran into the same problem.

When I run command: gffcompare -r ref.genes.gtf isoseq_flnc.Transcript.gff -o flnc
I got the following files:
flnc.isoseq_flnc.Transcript.gff.tmap
flnc.isoseq_flnc.Transcript.gff.refmap
flnc.tracking
flnc.annotated.gtf
flnc.loci
flnc.stats

Is the file "flnc.isoseq_flnc.Transcript.gff.tmap" same to the "flnc.tmap", or the "flnc.tmap" file was indeed not generated?

Thanks

**Comment by shizhuoxing** [comment]
@pigraul hi, "flnc.isoseq_flnc.Transcript.gff.tmap" same to the "flnc.tmap", i have modified this in this repo's README.
